# Screen rotation
rotation: left

# Camera rotation. Right, left, normal.
camera_rotation: left

# If displaying as a grid, use ints. Otherwise None or 1,1
grid_height: 1
grid_width: 1

# The duration of each new recording (seconds)
recording_duration: 5

# Monitor dimensions
monitor_height: 3840
monitor_width: 2160

# The amount that the new video contributes to the collage
alpha: 0.8

# Smoothing parameters for masks.
blur_size: 11
min_area: 500
temporal_alpha: 0.8

# NOTE: should eventually remove and infer num frames based on camera's natural frame rate.
fps: 10

# NOTE: this solves the problem where the code starts but the monitor is not yet turned on.
screen_rotation_freq: 1

# How often do we save a backup video (minutes)?
backup_video_save_freq : 60