# Screen rotation
rotation: normal #left

# Camera rotation. Right, left, normal.
camera_rotation: normal #left

# If displaying as a grid, use ints. Otherwise None or 1,1
grid_height: 1
grid_width: 1

# The duration of each new recording (seconds)
recording_duration: 5

# Monitor dimensions
monitor_height: 3840
monitor_width: 2160

# The amount that the new video contributes to the collage
alpha: 0.8

# Smoothing parameters for masks.
blur_size: 11
min_area: 500
temporal_alpha: 0.8

# FPS. NOTE: should eventually remove and infer num
# frames based on camera's natural frame rate.
# NOTE: this has an unpredictable effect.
fps: 10
